CORE-1893: update Grails hibernate4 plugin 4.3.10 (#755)
* Upgrade to Hibernate 4.3.10.Final

+--- org.grails.plugins:hibernate4:4.3.10
|    \--- org.hibernate:hibernate-validator:5.1.3.Final
|         \--- javax.validation:validation-api:1.1.0.Final
|         \--- com.fasterxml:classmate:1.0.0
|    \--- org.hibernate:hibernate-ehcache:4.3.10.Final
|         \--- org.hibernate:hibernate-core:4.3.10.Final
|              \--- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.0.0.Final
|              \--- antlr:antlr:2.7.7
|              \--- org.jboss:jandex:1.1.0.Final
|    \--- net.sf.ehcache:ehcache:2.9.0
|    \--- org.jboss.logging:jboss-logging:3.1.0.GA
|    \--- org.grails:grails-datastore-core:3.1.5.RELEASE
|    \--- org.grails:grails-datastore-gorm:3.1.5.RELEASE
|    \--- org.grails:grails-datastore-gorm-hibernate4:3.1.5.RELEASE
|         \--- org.grails:grails-datastore-gorm-hibernate-core:3.1.5.RELEASE
|              \--- org.grails:grails-datastore-gorm-plugin-support:3.1.5.RELEASE
|              \--- org.springframework:spring-orm:4.1.9.RELEASE
|         \--- org.hibernate.common:hibernate-commons-annotations:4.0.4.Final
|              \--- org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1
|         \--- dom4j:dom4j:1.6.1
|    \--- org.grails:grails-datastore-simple:3.1.5.RELEASE

* Fix cache.region.factory_class

As suggested by EHCache docs:
http://www.ehcache.org/documentation/2.8/integrations/hibernate#optional

* Update IntelliJ IDEA project files

* Hide error by adding Hibernate Transaction to {get,load}ViaJava()

org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.initialize(ModuleWithUI.java:187)
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.getStream(ModuleWithUI.java:154)
	at com.unifina.signalpath.ModuleWithUI$$ERxe6t56.pushToUiChannel(ModuleWithUI.java:57)
	at com.unifina.signalpath.utils.VariadicEventTable.initialize(VariadicEventTable.java:38)
	at com.unifina.signalpath.AbstractSignalPathModule$$E0.connectionsReady(AbstractSignalPathModule.java:310)
	at com.unifina.signalpath.SignalPath.connectionsReady(SignalPath.java:300)
	at com.unifina.signalpath.SignalPathRunner.run(SignalPathRunner.java:83)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 7 more

* Revert "Hide error by adding Hibernate Transaction to {get,load}ViaJava()"

This reverts commit b8009aebe34db498d8bd6acd31a12c3ce88ed3fa.

* Use InvokerHelper to call Groovy from Java

org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.initialize(ModuleWithUI.java:187)
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.getStream(ModuleWithUI.java:154)
	at com.unifina.signalpath.ModuleWithUI$$ERxe6t56.pushToUiChannel(ModuleWithUI.java:57)
	at com.unifina.signalpath.utils.VariadicEventTable.initialize(VariadicEventTable.java:38)
	at com.unifina.signalpath.AbstractSignalPathModule$$E0.connectionsReady(AbstractSignalPathModule.java:310)
	at com.unifina.signalpath.SignalPath.connectionsReady(SignalPath.java:300)
	at com.unifina.signalpath.SignalPathRunner.run(SignalPathRunner.java:83)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 7 more

* Revert "Use InvokerHelper to call Groovy from Java"

This reverts commit f3d7ccfc252de95355ed9b4683813ad7bbb6e0a6.

* Get the user via UserService

* Use singleton EhCache factory

* Update StreamrClient to version 2.0.0 (#802)

Major version bump comes with some interface changes. No new features in this PR, just updating the client and fixing the resulting compile errors.

* CORE-1954: mv secuser to user (#801)

* Rename SecUser to User

* Rename SecRole to Role

* Rename SecUserSecRole to UserRole

* add explanatory comment to criteria

* Find out in more detail how join request service is doing (#804)

* CORE-1951: Check that the join worked before responding to join request (#803)

* Add ThreadUtil

root@tomcat1 /var/log/tomcat7 # zgrep -n "Thread was interrupted while sleeping" catalina.out*.gz
root@tomcat1 /var/log/tomcat7 #

* CORE-1951: Check that the join worked before responding to join request

* Add Javadoc to ThreadUtil

* Use interval and timeout for join request check

* CORE-1955: Move domain classes to single package (#806)

* CORE-1947: New field "signupMethod" to "user" class (#808)

New field "signupMethod" to "user" class

* We set the value to "API" or "CORE" at signup. All users that exist already in the database are marked as "UNKNOWN".

* Support for Ethereum signup and situations where users are created via StreamrClientService

* BACK-15: update web3j (#811)

* Update org.web3j:core:4.5.9

Changelog https://github.com/web3j/web3j/releases/tag/v4.5.9

Notable fixes:
    - Fix WebSocketService connect https://github.com/web3j/web3j/pull/1110

* Update org.web3j:core:4.6.2

Changelog https://github.com/web3j/web3j/releases/tag/v4.6.2

Notable fixes:
    - Update ENS contract address https://github.com/web3j/web3j/pull/1153

* Update org.web3j:core:5.0.0

Changelog https://github.com/web3j/web3j/releases/tag/v5.0.0

* BACK-18: Delete CSV upload endpoints (#815)

Removed:

- endpoint /api/v1/streams/$id/uploadCsvFile
- endpoint /api/v1/streams/$id/confirmCsvFileUpload
- CsvUploadService and CSVImporter util
- related unit tests and REST tests

* CORE-1921: updating recreates permissions (#809)

Sending a PUT to the /products/id endpoint seems to recreate the public Permission rows, if the product is a free product.

* BACK-20 DU members should have STREAM_GET and STREAM_PUBLISH permissions (#814)

* DU members should have STREAM_GET and STREAM_PUBLISH permissions

* Update tests

Co-authored-by: Kare Nuorteva <kare.nuorteva@streamr.com>

* BACK-11: Remove Stream delete data endpoints (#816)

* BACK-11: Remove Stream delete data endpoints

* Fix review comments

* Add missing method

* BACK-21: Move REST API (UI Layer) classes to single package com.unifina.controller (#817)

* Move controller classes to a single package

* Drop service dependencies to controller

Controller classes can depend on services, but not the other way around.

* Remove empty file

Thanks, IntelliJ IDEA.

* Move misplaced classes to correct package

While at it, rename Spec to IntegrationSpec.

* Remove empty file

* BACK-22: Extract common Marketplace functionality to Product class methods (#818)

* Refactor code to use product.isFree()

Add unit test to document how it works.

* Extract product.isDeployed()

Add unit test to document how it works.

* Extract product.isPaid()

Add unit test to document how it works.

* Extract product.isUndeploying()

Add unit test to document how it works.

* Extract product.isNotDeployed()

Add unit test to document how it works.

* Add product.isDeploying()

Add unit test to document how it works.

* Revert "Add product.isDeploying()"

This reverts commit b03e12c0ccd3c348659155dcb3e6a0a170c24a3e.

* Revert "Extract product.isNotDeployed()"

This reverts commit 8071562c2e47a8c39677242dcb853de0c1ae6231.

* Revert "Extract product.isUndeploying()"

This reverts commit f12384b2e38d40dcc9a832524b08220758b45ffa.

* Revert "Extract product.isDeployed()"

This reverts commit f1203e9d481cd363079cddd02605ae75b24ff34d.

* Replace product.isPaid() with !product.isFree()

* BACK-3: Canvases use Ethereum-authenticated StreamrClient (#812)

* BACK-3: Canvases use Ethereum-authenticated StreamrClient instance to publish and subscribe

* Parse private key from IntegrationKey.json

* Fix unit tests

* Fix key generation

    - Update Streamr Java client 2.0.1

* Fix unit tests

* Fix private key generator

Need to pad with 0 so that the is always 64 chars

Co-authored-by: Teo Gebhard <teo@streamr.com>

* Reduce CI REST API logging output

* BACK-24: Prefix Data Union classes (#820)

* Rename ProxyException -> DataUnionProxyException

* Move DataUnionProxyException to com.unifina.service

* Rename JoinRequestException -> DataUnionJoinRequestException

* Move DataUnionJoinRequestException to com.unifina.service

* Rename UpdateDataUnionJoinRequestCommand -> DataUnionUpdateJoinRequestCommand

* Rename UnifinaCoreAPIFilters -> RESTAPIFilters (#822)

* BACK-6: Anonymous permissions should not be revoked when a stream belongs multiple free products (#825)

* BACK-25: Move StreamrApi annotation classes to controller (#821)

* Move StreamrApi annotation to controllers pkg

* Move REST API authentication to controller pkg

These classes are only used by other classes in the controller package.

* BACK-23: Remove unused classes (#819)

* Remove LoginRedirectValidator

* Remove DataRangeProvider

* Remove Poller

* Remove FileStorageAdapter

* Remove FeedNotFoundException

* Remove AbstractStreamListener

* BACK-33: Build Docker dev only on master (#829)

* Clean up .travis.yml

* Build Docker dev only on master

* Skip pull requests for Docker dev build

* BACK-27: Update REST E2E test libs (#826)

* Move Userish to domain (#831)

* BACK-7: Allow streams to be assigned to storage node addresses (#828)

We can assign storage node addresses for streams. The assignments are saved to the database and can be queried/updated via the REST API.

Added REST endpoints:

GET /api/v1/storageNodes/$storageNodeAddress/streams
GET /api/v1/streams/$streamId/storageNodes
POST /api/v1/streams/$streamId/storageNodes
DELETE /api/v1/streams/$streamId/storageNodes/$storageNodeAddress

* BACK-35: Remove com.unifina.exceptions package (#832)

* Move CanvasUnreachableException to com.unifina.service

* Move CyclicCanvasModuleExceptionMessage -> com.unifina.service

* Move InvalidStreamConfigException -> com.unifina.signalpath.utils

* Move JavaCompilerErrorMessage -> com.unifina.signalpath.custom

* Move ModuleExceptionMessage -> com.unifina.signalpath.custom

* Move NoExportedInputsException -> c.u.signalpath.map

* Move StreamFieldChangedException -> c.u.feed

* Move StreamNotFoundException -> c.u.signalpath

* Move UnauthorizedStreamException -> c.u.service

* Move UnexpectedApiResponseException -> c.u.service

* Move UserCreationFailedException -> c.u.service

* Convert CanvasUnreachableException to Groovy

* Cast exceptions null message to String

* BACK-31: Add Data Union version field to Product (#830)

Add "dataUnionVersion" field to Product and CreateProductCommand

* BACK-36: Move validators to com.unifina.domain package (#833)

* Move validators to domain pkg

* Optimize imports

* Fix merge

* BACK-38: Separate stress tests (#836)

Separate normal end-to-end tests and stress tests so that we can run either of those test suites easily.

There are three NPM scripts:

npm test - all tests
npm test:e2e - normal end-to-end tests
npm test:stress - stress tests

* Fix import

Co-authored-by: Teo Gebhard <teo@streamr.com>
Co-authored-by: Henri Pihkala <hpihkala@users.noreply.github.com>
Co-authored-by: Juuso Takalainen <juuso@streamr.network>