Fix: must get instead of load
I got following error when starting a canvas if load was used, because SecUser was a dummy GORM object of type SecUser_$$_javassist_41, and it won't have the function resolveToUserish, or whatever.

[SignalPathRunner [ki3hiKS2RcCtUuYEsj_yLQqgPnPZHyQYq9sHXycxVSSg]] ERROR signalpath.SignalPathRunner  - Error while running SignalPaths: [ki3hiKS2RcCtUuYEsj_yLQqgPnPZHyQYq9sHXycxVSSg]
org.hibernate.LazyInitializationException: could not initialize proxy - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:167)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:215)
	at org.codehaus.groovy.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer.invoke(GroovyAwareJavassistLazyInitializer.java:191)
	at com.unifina.domain.security.SecUser_$$_javassist_41.resolveToUserish(SecUser_$$_javassist_41.java)
	at com.unifina.security.Userish$resolveToUserish.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at com.unifina.security.Userish$resolveToUserish.call(Unknown Source)
	at com.unifina.service.PermissionService.systemGrant(PermissionService.groovy:196)
	at com.unifina.service.PermissionService$_systemGrantAll_closure3.doCall(PermissionService.groovy:183)
...
	at com.unifina.service.PermissionService.systemGrantAll(PermissionService.groovy:182)
	at com.unifina.service.PermissionService$$FastClassBySpringCGLIB$$b526b458.invoke(<generated>)
...
	at com.unifina.service.StreamService.createStream(StreamService.groovy:81)
...
	at com.unifina.signalpath.ModuleWithUI$UiChannel.initialize(ModuleWithUI.java:195)
	at com.unifina.signalpath.ModuleWithUI$UiChannel.getStream(ModuleWithUI.java:153)
	at com.unifina.signalpath.ModuleWithUI.pushToUiChannel(ModuleWithUI.java:69)
	at com.unifina.signalpath.utils.VariadicEventTable.pushToUiChannel(VariadicEventTable.java)
	at com.unifina.signalpath.utils.VariadicEventTable.initialize(VariadicEventTable.java:39)
	at com.unifina.signalpath.AbstractSignalPathModule.connectionsReady(AbstractSignalPathModule.java:317)
	at com.unifina.signalpath.ModuleWithUI.connectionsReady(ModuleWithUI.java)
	at com.unifina.signalpath.utils.VariadicEventTable.connectionsReady(VariadicEventTable.java)
	at com.unifina.signalpath.SignalPath.connectionsReady(SignalPath.java:281)
	at com.unifina.signalpath.SignalPathRunner.run(SignalPathRunner.groovy:110)