BACK-179: Node 16 update (#989)
* style(e2e-test): remove unused @ts-expect-error

* chore(e2e-test): Streamr Javascript client 5.4.1

* chore(e2e-test): remove unused async-wait-until

* chore(e2e-test): remove unused sleep-promise

* style(e2e-test): move tests to src dir

* chore(e2e-test): update Node 16.2

Npm install/ci require an additional command line flag to prevent
following compilation error: CXXFLAGS=-std=c++14

npm ERR! In file included from /Users/kkn/.node-gyp/16.2.0/include/node/v8.h:30:
npm ERR! /Users/kkn/.node-gyp/16.2.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv

Added npm_install recipe for convenience.

* chore(ci): remove old npm install