Hide error by adding Hibernate Transaction to {get,load}ViaJava()
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.initialize(ModuleWithUI.java:187)
	at com.unifina.signalpath.ModuleWithUI$UiChannel$$ERxe6t56.getStream(ModuleWithUI.java:154)
	at com.unifina.signalpath.ModuleWithUI$$ERxe6t56.pushToUiChannel(ModuleWithUI.java:57)
	at com.unifina.signalpath.utils.VariadicEventTable.initialize(VariadicEventTable.java:38)
	at com.unifina.signalpath.AbstractSignalPathModule$$E0.connectionsReady(AbstractSignalPathModule.java:310)
	at com.unifina.signalpath.SignalPath.connectionsReady(SignalPath.java:300)
	at com.unifina.signalpath.SignalPathRunner.run(SignalPathRunner.java:83)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 7 more